language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install: 
  - pip install -r test_requirements.txt --use-mirrors
  - pip install coveralls
script:
  - cd influxdb_metrix/tests
  - ./runtests.py
  - mv .coverage ../../
  - cd ../../
after_success: 
  - coveralls
